"""empty message

Revision ID: 66f990e22964
Revises: c7519706dba7
Create Date: 2020-04-13 00:05:45.277491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f990e22964'
down_revision = 'c7519706dba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recriut', sa.Column('cohort_recruit', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('recriut', 'cohort')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recriut', sa.Column('cohort', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('recriut', 'cohort_recruit')
    # ### end Alembic commands ###
