"""empty message

Revision ID: 75d1f711062a
Revises: 0093b4f1eaa1
Create Date: 2020-04-12 23:05:59.498524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d1f711062a'
down_revision = '0093b4f1eaa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recriut', sa.Column('personal_email_address', sa.VARCHAR(length=100), nullable=True))
    op.create_unique_constraint(None, 'recriut', ['personal_email_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recriut', type_='unique')
    op.drop_column('recriut', 'personal_email_address')
    # ### end Alembic commands ###
