"""empty message

Revision ID: 9cb423cae309
Revises: 96724beb7986
Create Date: 2020-04-12 23:36:00.174442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb423cae309'
down_revision = '96724beb7986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recriut', sa.Column('rocketchat_user', sa.String(length=100), nullable=True))
    op.drop_column('recriut', 'chatname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recriut', sa.Column('chatname', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('recriut', 'rocketchat_user')
    # ### end Alembic commands ###
