"""empty message

Revision ID: c7519706dba7
Revises: 9cb423cae309
Create Date: 2020-04-12 23:53:56.370650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7519706dba7'
down_revision = '9cb423cae309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recriut', sa.Column('cohort', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('recriut', 'chort')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recriut', sa.Column('chort', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('recriut', 'cohort')
    # ### end Alembic commands ###
